site_name: My Website
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highligh
    - content.tabs.link
    - content.code.annotation
    - content.code.copy